# Nixpacks configuration for Astro blog
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build"]
